# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\LiWei\My Documents\My DBank\programming\mycode\python\DirAss\mainform.ui'
#
# Created: Fri Apr  8 20:12:43 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(600, 400))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("幼圆"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rb1 = QtGui.QRadioButton(self.centralwidget)
        self.rb1.setObjectName(_fromUtf8("rb1"))
        self.buttonGroup = QtGui.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.rb1)
        self.horizontalLayout.addWidget(self.rb1)
        self.rb2 = QtGui.QRadioButton(self.centralwidget)
        self.rb2.setChecked(True)
        self.rb2.setObjectName(_fromUtf8("rb2"))
        self.buttonGroup.addButton(self.rb2)
        self.horizontalLayout.addWidget(self.rb2)
        self.rb3 = QtGui.QRadioButton(self.centralwidget)
        self.rb3.setObjectName(_fromUtf8("rb3"))
        self.buttonGroup.addButton(self.rb3)
        self.horizontalLayout.addWidget(self.rb3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.btn_open = QtGui.QPushButton(self.centralwidget)
        self.btn_open.setObjectName(_fromUtf8("btn_open"))
        self.verticalLayout.addWidget(self.btn_open)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.te_dirs = QtGui.QTextEdit(self.centralwidget)
        self.te_dirs.setObjectName(_fromUtf8("te_dirs"))
        self.verticalLayout.addWidget(self.te_dirs)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.te_bmd = QtGui.QTextEdit(self.centralwidget)
        self.te_bmd.setObjectName(_fromUtf8("te_bmd"))
        self.verticalLayout_2.addWidget(self.te_bmd)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_create = QtGui.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.btn_create.setFont(font)
        self.btn_create.setObjectName(_fromUtf8("btn_create"))
        self.horizontalLayout_2.addWidget(self.btn_create)
        self.btn_savebmd = QtGui.QPushButton(self.centralwidget)
        self.btn_savebmd.setObjectName(_fromUtf8("btn_savebmd"))
        self.horizontalLayout_2.addWidget(self.btn_savebmd)
        self.btn_savedirs = QtGui.QPushButton(self.centralwidget)
        self.btn_savedirs.setObjectName(_fromUtf8("btn_savedirs"))
        self.horizontalLayout_2.addWidget(self.btn_savedirs)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        MainWindow.setMenuBar(self.menubar)
        self.action_XML = QtGui.QAction(MainWindow)
        self.action_XML.setObjectName(_fromUtf8("action_XML"))
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName(_fromUtf8("action"))
        self.action_BMD = QtGui.QAction(MainWindow)
        self.action_BMD.setObjectName(_fromUtf8("action_BMD"))
        self.action_2 = QtGui.QAction(MainWindow)
        self.action_2.setObjectName(_fromUtf8("action_2"))
        self.menu_about = QtGui.QAction(MainWindow)
        self.menu_about.setObjectName(_fromUtf8("menu_about"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.menu.addAction(self.action_XML)
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_BMD)
        self.menu.addAction(self.action_3)
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu_2.addAction(self.menu_about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.menu_about, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.showAbout)
        QtCore.QObject.connect(self.btn_open, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.open)
        QtCore.QObject.connect(self.btn_create, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.createdirs)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "多文件夹助手", None, QtGui.QApplication.UnicodeUTF8))
        self.rb1.setText(QtGui.QApplication.translate("MainWindow", "BMD", None, QtGui.QApplication.UnicodeUTF8))
        self.rb2.setText(QtGui.QApplication.translate("MainWindow", "文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.rb3.setText(QtGui.QApplication.translate("MainWindow", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_open.setText(QtGui.QApplication.translate("MainWindow", "打开", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "文件夹结构", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "bmd描述", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_create.setText(QtGui.QApplication.translate("MainWindow", "建立目录", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_savebmd.setText(QtGui.QApplication.translate("MainWindow", "保存bmd", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_savedirs.setText(QtGui.QApplication.translate("MainWindow", "保存文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "文件", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "帮助", None, QtGui.QApplication.UnicodeUTF8))
        self.action_XML.setText(QtGui.QApplication.translate("MainWindow", "打开BMD", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "打开文件夹", None, QtGui.QApplication.UnicodeUTF8))
        self.action_BMD.setText(QtGui.QApplication.translate("MainWindow", "保存BMD", None, QtGui.QApplication.UnicodeUTF8))
        self.action_2.setText(QtGui.QApplication.translate("MainWindow", "退出", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_about.setText(QtGui.QApplication.translate("MainWindow", "关于本程序", None, QtGui.QApplication.UnicodeUTF8))
        self.action_3.setText(QtGui.QApplication.translate("MainWindow", "保存文件夹", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

